import fs from 'fs';

const outPath = new URL('../components/price-comparison-section.tsx', import.meta.url);
const c = '</' + 'div>';

const lines = [
  "'use client';",
  '',
  "import { useMemo } from 'react';",
  "import Link from 'next/link';",
  "import { Product } from '@/lib/types';",
  "import { formatPrice, getAllProducts, getAllStores } from '@/lib/services';",
  "import { PriceComparison } from '@/components/price-comparison';",
  "import { Button } from '@/components/ui/button';",
  "import { cn } from '@/lib/utils';",
  "import { ArrowRight, RotateCcw } from 'lucide-react';",
  '',
  'interface PriceComparisonSectionProps {',
  '  initialProduct: Product;',
  '  activeProduct: Product;',
  '  onSelectProduct: (product: Product) => void;',
  '}',
  '',
  'export function PriceComparisonSection({',
  '  initialProduct,',
  '  activeProduct,',
  '  onSelectProduct,',
  '}: PriceComparisonSectionProps) {',
  '  const stores = getAllStores();',
  '',
  '  const pickerProducts = useMemo(() => {',
  '    return getAllProducts()',
  "      .filter((p) => p.category === 'Fashion' || p.category === 'Beauty')",
  '      .sort((a, b) => b.trendingScore - a.trendingScore)',
  '      .slice(0, 12);',
  '  }, []);',
  '',
  '  const isOriginal = activeProduct.id === initialProduct.id;',
  '',
  '  return (',
  '    <div className="space-y-6">',
  '      <div className="rounded-xl border border-border bg-muted/20 p-4 md:p-5">',
  '        <div className="mb-4 flex flex-wrap items-end justify-between gap-3">',
  '          <div>',
  '            <h3 className="text-lg font-semibold text-foreground">Compare products</h3>',
  '            <p className="text-sm text-muted-foreground">Tap a product — it updates the view above and prices below</p>',
  c,
  '          {!isOriginal && (',
  '            <Button type="button" variant="outline" size="sm" onClick={() => onSelectProduct(initialProduct)}>',
  '              <RotateCcw className="mr-1.5 h-3.5 w-3.5" /> Reset',
  '            </Button>',
  '          )}',
  c,
  '        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">',
  '          {pickerProducts.map((p) => {',
  '            const selected = p.id === activeProduct.id;',
  '            return (',
  '              <button',
  '                key={p.id}',
  '                type="button"',
  '                onClick={() => onSelectProduct(p)}',
  '                className={cn(',
  "                  'group flex flex-col overflow-hidden rounded-lg border bg-card text-left transition-all hover:shadow-md',",
  "                  selected ? 'border-primary ring-2 ring-primary/30' : 'border-border hover:border-primary/40'",
  '                )}',
  '              >',
  '                <div className="aspect-[3/4] overflow-hidden bg-muted">',
  '                  <img',
  '                    src={p.image}',
  '                    alt={p.name}',
  '                    className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"',
  '                    loading="lazy"',
  "                    onError={(e) => { e.currentTarget.src = '/placeholder.svg'; }}",
  '                  />',
  c,
  '                <div className="space-y-0.5 p-2.5">',
  '                  <p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">{p.brand}</p>',
  '                  <p className="line-clamp-2 text-xs font-medium leading-snug text-foreground">{p.name}</p>',
  '                  <p className="text-sm font-semibold text-primary">{formatPrice(p.lowestPrice)}</p>',
  c,
  '              </button>',
  '            );',
  '          })}',
  c,
  '        <div className="mt-4 flex flex-wrap gap-2">',
  '          <Button asChild size="sm" className="rounded-full">',
  '            <Link href={`/product/${activeProduct.id}`}>',
  '              View full product',
  '              <ArrowRight className="ml-1.5 h-4 w-4" />',
  '            </Link>',
  '          </Button>',
  c,
  c,
  '      <PriceComparison product={activeProduct} stores={stores} />',
  c,
  '  );',
  '}',
  '',
];

fs.writeFileSync(outPath, lines.join('\n'));
console.log('written', lines.length);
